In [1]:
from scipy.io import arff
import pandas as pd

In [2]:
data, met = arff.loadarff("emotions/emotions-train.arff")

In [3]:
df_train = pd.DataFrame(data)

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 78 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Mean_Acc1298_Mean_Mem40_Centroid  391 non-null    float64
 1   Mean_Acc1298_Mean_Mem40_Rolloff   391 non-null    float64
 2   Mean_Acc1298_Mean_Mem40_Flux      391 non-null    float64
 3   Mean_Acc1298_Mean_Mem40_MFCC_0    391 non-null    float64
 4   Mean_Acc1298_Mean_Mem40_MFCC_1    391 non-null    float64
 5   Mean_Acc1298_Mean_Mem40_MFCC_2    391 non-null    float64
 6   Mean_Acc1298_Mean_Mem40_MFCC_3    391 non-null    float64
 7   Mean_Acc1298_Mean_Mem40_MFCC_4    391 non-null    float64
 8   Mean_Acc1298_Mean_Mem40_MFCC_5    391 non-null    float64
 9   Mean_Acc1298_Mean_Mem40_MFCC_6    391 non-null    float64
 10  Mean_Acc1298_Mean_Mem40_MFCC_7    391 non-null    float64
 11  Mean_Acc1298_Mean_Mem40_MFCC_8    391 non-null    float64
 12  Mean_Acc1298_Mean_Mem40_MFCC_9    391 non-null    float64
 13  Mean_Acc1298_Mean_Mem40_MFCC_10   391 non-null    float64
 14  Mean_Acc1298_Mean_Mem40_MFCC_11   391 non-null    float64
 15  Mean_Acc1298_Mean_Mem40_MFCC_12   391 non-null    float64
 16  Mean_Acc1298_Std_Mem40_Centroid   391 non-null    float64
 17  Mean_Acc1298_Std_Mem40_Rolloff    391 non-null    float64
 18  Mean_Acc1298_Std_Mem40_Flux       391 non-null    float64
 19  Mean_Acc1298_Std_Mem40_MFCC_0     391 non-null    float64
 20  Mean_Acc1298_Std_Mem40_MFCC_1     391 non-null    float64
 21  Mean_Acc1298_Std_Mem40_MFCC_2     391 non-null    float64
 22  Mean_Acc1298_Std_Mem40_MFCC_3     391 non-null    float64
 23  Mean_Acc1298_Std_Mem40_MFCC_4     391 non-null    float64
 24  Mean_Acc1298_Std_Mem40_MFCC_5     391 non-null    float64
 25  Mean_Acc1298_Std_Mem40_MFCC_6     391 non-null    float64
 26  Mean_Acc1298_Std_Mem40_MFCC_7     391 non-null    float64
 27  Mean_Acc1298_Std_Mem40_MFCC_8     391 non-null    float64
 28  Mean_Acc1298_Std_Mem40_MFCC_9     391 non-null    float64
 29  Mean_Acc1298_Std_Mem40_MFCC_10    391 non-null    float64
 30  Mean_Acc1298_Std_Mem40_MFCC_11    391 non-null    float64
 31  Mean_Acc1298_Std_Mem40_MFCC_12    391 non-null    float64
 32  Std_Acc1298_Mean_Mem40_Centroid   391 non-null    float64
 33  Std_Acc1298_Mean_Mem40_Rolloff    391 non-null    float64
 34  Std_Acc1298_Mean_Mem40_Flux       391 non-null    float64
 35  Std_Acc1298_Mean_Mem40_MFCC_0     391 non-null    float64
 36  Std_Acc1298_Mean_Mem40_MFCC_1     391 non-null    float64
 37  Std_Acc1298_Mean_Mem40_MFCC_2     391 non-null    float64
 38  Std_Acc1298_Mean_Mem40_MFCC_3     391 non-null    float64
 39  Std_Acc1298_Mean_Mem40_MFCC_4     391 non-null    float64
 40  Std_Acc1298_Mean_Mem40_MFCC_5     391 non-null    float64
 41  Std_Acc1298_Mean_Mem40_MFCC_6     391 non-null    float64
 42  Std_Acc1298_Mean_Mem40_MFCC_7     391 non-null    float64
 43  Std_Acc1298_Mean_Mem40_MFCC_8     391 non-null    float64
 44  Std_Acc1298_Mean_Mem40_MFCC_9     391 non-null    float64
 45  Std_Acc1298_Mean_Mem40_MFCC_10    391 non-null    float64
 46  Std_Acc1298_Mean_Mem40_MFCC_11    391 non-null    float64
 47  Std_Acc1298_Mean_Mem40_MFCC_12    391 non-null    float64
 48  Std_Acc1298_Std_Mem40_Centroid    391 non-null    float64
 49  Std_Acc1298_Std_Mem40_Rolloff     391 non-null    float64
 50  Std_Acc1298_Std_Mem40_Flux        391 non-null    float64
 51  Std_Acc1298_Std_Mem40_MFCC_0      391 non-null    float64
 52  Std_Acc1298_Std_Mem40_MFCC_1      391 non-null    float64
 53  Std_Acc1298_Std_Mem40_MFCC_2      391 non-null    float64
 54  Std_Acc1298_Std_Mem40_MFCC_3      391 non-null    float64
 55  Std_Acc1298_Std_Mem40_MFCC_4      391 non-null    float64
 56  Std_Acc1298_Std_Mem40_MFCC_5      391 non-null    float64
 57  Std_Acc1298_Std_Mem40_MFCC_6      391 non-null    float64
 58  Std_Acc1298_Std_Mem40_MFCC_7      391 non-null    float64
 59  Std_Acc1298_Std_Mem40_MFCC_8      391 non-null    float64
 60  Std_Acc1298_Std_Mem40_MFCC_9      391 non-null    float64
 61  Std_Acc1298_Std_Mem40_MFCC_10     391 non-null    float64
 62  Std_Acc1298_Std_Mem40_MFCC_11     391 non-null    float64
 63  Std_Acc1298_Std_Mem40_MFCC_12     391 non-null    float64
 64  BH_LowPeakAmp                     391 non-null    float64
 65  BH_LowPeakBPM                     391 non-null    float64
 66  BH_HighPeakAmp                    391 non-null    float64
 67  BH_HighPeakBPM                    391 non-null    float64
 68  BH_HighLowRatio                   391 non-null    float64
 69  BHSUM1                            391 non-null    float64
 70  BHSUM2                            391 non-null    float64
 71  BHSUM3                            391 non-null    float64
 72  amazed-suprised                   391 non-null    object
 73  happy-pleased                     391 non-null    object
 74  relaxing-calm                     391 non-null    object
 75  quiet-still                       391 non-null    object
 76  sad-lonely                        391 non-null    object
 77  angry-aggresive                   391 non-null    object
dtypes: float64(72), object(6)
memory usage: 238.4+ KB

In [5]:
emo_cols= [
    'amazed-suprised',
    'happy-pleased',
    'relaxing-calm',
    'quiet-still',
    'sad-lonely',
    'angry-aggresive'
]

In [6]:
#change type of byte variables to string - Yes or No
for col in emo_cols:
    df_train[col] = df_train[col].str.decode('utf-8')

    df_train[col] = df_train[col].map(
        {'0': '0',
        '1': '1'}
    )

In [7]:
df_train.head().T

,0,1,2,3,4
Mean_Acc1298_Mean_Mem40_Centroid,0.034741,0.081374,0.110545,0.042481,0.07455
Mean_Acc1298_Mean_Mem40_Rolloff,0.089665,0.272747,0.273567,0.199281,0.14088
Mean_Acc1298_Mean_Mem40_Flux,0.091225,0.085733,0.08441,0.093447,0.079789
Mean_Acc1298_Mean_Mem40_MFCC_0,-73.302422,-62.584437,-65.235325,-80.305152,-93.697749
Mean_Acc1298_Mean_Mem40_MFCC_1,6.215179,3.183163,2.794964,5.824409,5.543229
...,...,...,...,...,...
happy-pleased,1,0,1,0,0
relaxing-calm,1,0,0,1,0
quiet-still,0,0,0,0,1
sad-lonely,0,0,0,0,0
angry-aggresive,0,1,1,0,0

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 78 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Mean_Acc1298_Mean_Mem40_Centroid  391 non-null    float64
 1   Mean_Acc1298_Mean_Mem40_Rolloff   391 non-null    float64
 2   Mean_Acc1298_Mean_Mem40_Flux      391 non-null    float64
 3   Mean_Acc1298_Mean_Mem40_MFCC_0    391 non-null    float64
 4   Mean_Acc1298_Mean_Mem40_MFCC_1    391 non-null    float64
 5   Mean_Acc1298_Mean_Mem40_MFCC_2    391 non-null    float64
 6   Mean_Acc1298_Mean_Mem40_MFCC_3    391 non-null    float64
 7   Mean_Acc1298_Mean_Mem40_MFCC_4    391 non-null    float64
 8   Mean_Acc1298_Mean_Mem40_MFCC_5    391 non-null    float64
 9   Mean_Acc1298_Mean_Mem40_MFCC_6    391 non-null    float64
 10  Mean_Acc1298_Mean_Mem40_MFCC_7    391 non-null    float64
 11  Mean_Acc1298_Mean_Mem40_MFCC_8    391 non-null    float64
 12  Mean_Acc1298_Mean_Mem40_MFCC_9    391 non-null    float64
 13  Mean_Acc1298_Mean_Mem40_MFCC_10   391 non-null    float64
 14  Mean_Acc1298_Mean_Mem40_MFCC_11   391 non-null    float64
 15  Mean_Acc1298_Mean_Mem40_MFCC_12   391 non-null    float64
 16  Mean_Acc1298_Std_Mem40_Centroid   391 non-null    float64
 17  Mean_Acc1298_Std_Mem40_Rolloff    391 non-null    float64
 18  Mean_Acc1298_Std_Mem40_Flux       391 non-null    float64
 19  Mean_Acc1298_Std_Mem40_MFCC_0     391 non-null    float64
 20  Mean_Acc1298_Std_Mem40_MFCC_1     391 non-null    float64
 21  Mean_Acc1298_Std_Mem40_MFCC_2     391 non-null    float64
 22  Mean_Acc1298_Std_Mem40_MFCC_3     391 non-null    float64
 23  Mean_Acc1298_Std_Mem40_MFCC_4     391 non-null    float64
 24  Mean_Acc1298_Std_Mem40_MFCC_5     391 non-null    float64
 25  Mean_Acc1298_Std_Mem40_MFCC_6     391 non-null    float64
 26  Mean_Acc1298_Std_Mem40_MFCC_7     391 non-null    float64
 27  Mean_Acc1298_Std_Mem40_MFCC_8     391 non-null    float64
 28  Mean_Acc1298_Std_Mem40_MFCC_9     391 non-null    float64
 29  Mean_Acc1298_Std_Mem40_MFCC_10    391 non-null    float64
 30  Mean_Acc1298_Std_Mem40_MFCC_11    391 non-null    float64
 31  Mean_Acc1298_Std_Mem40_MFCC_12    391 non-null    float64
 32  Std_Acc1298_Mean_Mem40_Centroid   391 non-null    float64
 33  Std_Acc1298_Mean_Mem40_Rolloff    391 non-null    float64
 34  Std_Acc1298_Mean_Mem40_Flux       391 non-null    float64
 35  Std_Acc1298_Mean_Mem40_MFCC_0     391 non-null    float64
 36  Std_Acc1298_Mean_Mem40_MFCC_1     391 non-null    float64
 37  Std_Acc1298_Mean_Mem40_MFCC_2     391 non-null    float64
 38  Std_Acc1298_Mean_Mem40_MFCC_3     391 non-null    float64
 39  Std_Acc1298_Mean_Mem40_MFCC_4     391 non-null    float64
 40  Std_Acc1298_Mean_Mem40_MFCC_5     391 non-null    float64
 41  Std_Acc1298_Mean_Mem40_MFCC_6     391 non-null    float64
 42  Std_Acc1298_Mean_Mem40_MFCC_7     391 non-null    float64
 43  Std_Acc1298_Mean_Mem40_MFCC_8     391 non-null    float64
 44  Std_Acc1298_Mean_Mem40_MFCC_9     391 non-null    float64
 45  Std_Acc1298_Mean_Mem40_MFCC_10    391 non-null    float64
 46  Std_Acc1298_Mean_Mem40_MFCC_11    391 non-null    float64
 47  Std_Acc1298_Mean_Mem40_MFCC_12    391 non-null    float64
 48  Std_Acc1298_Std_Mem40_Centroid    391 non-null    float64
 49  Std_Acc1298_Std_Mem40_Rolloff     391 non-null    float64
 50  Std_Acc1298_Std_Mem40_Flux        391 non-null    float64
 51  Std_Acc1298_Std_Mem40_MFCC_0      391 non-null    float64
 52  Std_Acc1298_Std_Mem40_MFCC_1      391 non-null    float64
 53  Std_Acc1298_Std_Mem40_MFCC_2      391 non-null    float64
 54  Std_Acc1298_Std_Mem40_MFCC_3      391 non-null    float64
 55  Std_Acc1298_Std_Mem40_MFCC_4      391 non-null    float64
 56  Std_Acc1298_Std_Mem40_MFCC_5      391 non-null    float64
 57  Std_Acc1298_Std_Mem40_MFCC_6      391 non-null    float64
 58  Std_Acc1298_Std_Mem40_MFCC_7      391 non-null    float64
 59  Std_Acc1298_Std_Mem40_MFCC_8      391 non-null    float64
 60  Std_Acc1298_Std_Mem40_MFCC_9      391 non-null    float64
 61  Std_Acc1298_Std_Mem40_MFCC_10     391 non-null    float64
 62  Std_Acc1298_Std_Mem40_MFCC_11     391 non-null    float64
 63  Std_Acc1298_Std_Mem40_MFCC_12     391 non-null    float64
 64  BH_LowPeakAmp                     391 non-null    float64
 65  BH_LowPeakBPM                     391 non-null    float64
 66  BH_HighPeakAmp                    391 non-null    float64
 67  BH_HighPeakBPM                    391 non-null    float64
 68  BH_HighLowRatio                   391 non-null    float64
 69  BHSUM1                            391 non-null    float64
 70  BHSUM2                            391 non-null    float64
 71  BHSUM3                            391 non-null    float64
 72  amazed-suprised                   391 non-null    object
 73  happy-pleased                     391 non-null    object
 74  relaxing-calm                     391 non-null    object
 75  quiet-still                       391 non-null    object
 76  sad-lonely                        391 non-null    object
 77  angry-aggresive                   391 non-null    object
dtypes: float64(72), object(6)
memory usage: 238.4+ KB

In [9]:
df_train.describe(include='all')

,Mean_Acc1298_Mean_Mem40_Centroid,Mean_Acc1298_Mean_Mem40_Rolloff,Mean_Acc1298_Mean_Mem40_Flux,Mean_Acc1298_Mean_Mem40_MFCC_0,Mean_Acc1298_Mean_Mem40_MFCC_1,Mean_Acc1298_Mean_Mem40_MFCC_2,Mean_Acc1298_Mean_Mem40_MFCC_3,Mean_Acc1298_Mean_Mem40_MFCC_4,Mean_Acc1298_Mean_Mem40_MFCC_5,Mean_Acc1298_Mean_Mem40_MFCC_6,...,BH_HighLowRatio,BHSUM1,BHSUM2,BHSUM3,amazed-suprised,happy-pleased,relaxing-calm,quiet-still,sad-lonely,angry-aggresive
count,391.000000,391.000000,391.000000,391.000000,391.000000,391.000000,391.000000,391.000000,391.000000,391.000000,...,391.000000,391.000000,391.000000,391.000000,391,391,391,391,391,391
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2,2,2,2,2,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,272,284,223,302,296,260
mean,0.069977,0.206432,0.086680,-73.024495,4.821225,0.596974,1.666577,0.642598,0.840467,0.509918,...,2.097187,0.442414,0.377433,0.995528,NaN,NaN,NaN,NaN,NaN,NaN
std,0.031177,0.122262,0.010021,7.430150,2.062840,1.027836,0.634509,0.454925,0.360613,0.302477,...,0.321483,0.362775,0.393236,0.690449,NaN,NaN,NaN,NaN,NaN,NaN
min,0.010201,0.038729,0.070932,-99.090802,0.051474,-2.235707,-0.604609,-1.143864,-0.237114,-0.444623,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.045485,0.115491,0.079328,-76.966920,3.288905,-0.095958,1.277283,0.387128,0.607217,0.327448,...,2.000000,0.186655,0.097626,0.509127,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.066195,0.176479,0.085116,-72.328740,4.384101,0.587896,1.706145,0.645530,0.818205,0.524997,...,2.000000,0.343781,0.242964,0.831004,NaN,NaN,NaN,NaN,NaN,NaN
75%,0.087197,0.271220,0.092088,-68.548188,6.277184,1.259581,2.073187,0.925979,1.053052,0.696944,...,2.000000,0.563363,0.542230,1.271616,NaN,NaN,NaN,NaN,NaN,NaN
max,0.188637,0.698277,0.159460,-56.297652,11.853471,3.910873,4.382370,2.046689,2.358098,1.484489,...,3.000000,1.795128,1.762948,3.422899,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data_test, meta_test = arff.loadarff("emotions/emotions-test.arff")

In [11]:
df_test = pd.DataFrame(data_test)

In [12]:
df_test.head()

,Mean_Acc1298_Mean_Mem40_Centroid,Mean_Acc1298_Mean_Mem40_Rolloff,Mean_Acc1298_Mean_Mem40_Flux,Mean_Acc1298_Mean_Mem40_MFCC_0,Mean_Acc1298_Mean_Mem40_MFCC_1,Mean_Acc1298_Mean_Mem40_MFCC_2,Mean_Acc1298_Mean_Mem40_MFCC_3,Mean_Acc1298_Mean_Mem40_MFCC_4,Mean_Acc1298_Mean_Mem40_MFCC_5,Mean_Acc1298_Mean_Mem40_MFCC_6,...,BH_HighLowRatio,BHSUM1,BHSUM2,BHSUM3,amazed-suprised,happy-pleased,relaxing-calm,quiet-still,sad-lonely,angry-aggresive
0,0.036299,0.064986,0.082104,-72.710462,7.920220,0.134279,2.546373,0.671063,1.589821,0.576485,...,2.0,0.095982,0.520006,0.677943,b'0',b'0',b'1',b'1',b'1',b'0'
1,0.161218,0.467820,0.096983,-71.298043,1.176349,1.871744,1.097346,0.641059,0.372797,0.991050,...,2.0,0.752210,0.576382,1.477141,b'1',b'0',b'0',b'0',b'0',b'1'
2,0.115987,0.336879,0.079068,-64.570939,2.339044,0.714859,1.792451,0.611347,0.287022,0.772846,...,2.0,0.488375,0.004603,1.147727,b'0',b'0',b'0',b'0',b'1',b'0'
3,0.086016,0.141845,0.081554,-81.141092,6.714252,-1.338896,1.326248,0.340032,1.290664,0.337209,...,2.0,0.430059,0.102757,1.276632,b'0',b'1',b'1',b'0',b'0',b'0'
4,0.063232,0.140621,0.082097,-66.596131,5.594724,0.350716,1.023655,0.439544,0.855564,0.414784,...,2.0,1.788567,0.032760,3.076057,b'0',b'0',b'0',b'0',b'1',b'0'

In [13]:
#change type of byte variables to string - Yes or No
for col in emo_cols:
    df_test[col] = df_test[col].str.decode('utf-8')

    df_test[col] = df_test[col].map(
        {'0': '0',
        '1': '1'}
    )

In [14]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 78 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Mean_Acc1298_Mean_Mem40_Centroid  202 non-null    float64
 1   Mean_Acc1298_Mean_Mem40_Rolloff   202 non-null    float64
 2   Mean_Acc1298_Mean_Mem40_Flux      202 non-null    float64
 3   Mean_Acc1298_Mean_Mem40_MFCC_0    202 non-null    float64
 4   Mean_Acc1298_Mean_Mem40_MFCC_1    202 non-null    float64
 5   Mean_Acc1298_Mean_Mem40_MFCC_2    202 non-null    float64
 6   Mean_Acc1298_Mean_Mem40_MFCC_3    202 non-null    float64
 7   Mean_Acc1298_Mean_Mem40_MFCC_4    202 non-null    float64
 8   Mean_Acc1298_Mean_Mem40_MFCC_5    202 non-null    float64
 9   Mean_Acc1298_Mean_Mem40_MFCC_6    202 non-null    float64
 10  Mean_Acc1298_Mean_Mem40_MFCC_7    202 non-null    float64
 11  Mean_Acc1298_Mean_Mem40_MFCC_8    202 non-null    float64
 12  Mean_Acc1298_Mean_Mem40_MFCC_9    202 non-null    float64
 13  Mean_Acc1298_Mean_Mem40_MFCC_10   202 non-null    float64
 14  Mean_Acc1298_Mean_Mem40_MFCC_11   202 non-null    float64
 15  Mean_Acc1298_Mean_Mem40_MFCC_12   202 non-null    float64
 16  Mean_Acc1298_Std_Mem40_Centroid   202 non-null    float64
 17  Mean_Acc1298_Std_Mem40_Rolloff    202 non-null    float64
 18  Mean_Acc1298_Std_Mem40_Flux       202 non-null    float64
 19  Mean_Acc1298_Std_Mem40_MFCC_0     202 non-null    float64
 20  Mean_Acc1298_Std_Mem40_MFCC_1     202 non-null    float64
 21  Mean_Acc1298_Std_Mem40_MFCC_2     202 non-null    float64
 22  Mean_Acc1298_Std_Mem40_MFCC_3     202 non-null    float64
 23  Mean_Acc1298_Std_Mem40_MFCC_4     202 non-null    float64
 24  Mean_Acc1298_Std_Mem40_MFCC_5     202 non-null    float64
 25  Mean_Acc1298_Std_Mem40_MFCC_6     202 non-null    float64
 26  Mean_Acc1298_Std_Mem40_MFCC_7     202 non-null    float64
 27  Mean_Acc1298_Std_Mem40_MFCC_8     202 non-null    float64
 28  Mean_Acc1298_Std_Mem40_MFCC_9     202 non-null    float64
 29  Mean_Acc1298_Std_Mem40_MFCC_10    202 non-null    float64
 30  Mean_Acc1298_Std_Mem40_MFCC_11    202 non-null    float64
 31  Mean_Acc1298_Std_Mem40_MFCC_12    202 non-null    float64
 32  Std_Acc1298_Mean_Mem40_Centroid   202 non-null    float64
 33  Std_Acc1298_Mean_Mem40_Rolloff    202 non-null    float64
 34  Std_Acc1298_Mean_Mem40_Flux       202 non-null    float64
 35  Std_Acc1298_Mean_Mem40_MFCC_0     202 non-null    float64
 36  Std_Acc1298_Mean_Mem40_MFCC_1     202 non-null    float64
 37  Std_Acc1298_Mean_Mem40_MFCC_2     202 non-null    float64
 38  Std_Acc1298_Mean_Mem40_MFCC_3     202 non-null    float64
 39  Std_Acc1298_Mean_Mem40_MFCC_4     202 non-null    float64
 40  Std_Acc1298_Mean_Mem40_MFCC_5     202 non-null    float64
 41  Std_Acc1298_Mean_Mem40_MFCC_6     202 non-null    float64
 42  Std_Acc1298_Mean_Mem40_MFCC_7     202 non-null    float64
 43  Std_Acc1298_Mean_Mem40_MFCC_8     202 non-null    float64
 44  Std_Acc1298_Mean_Mem40_MFCC_9     202 non-null    float64
 45  Std_Acc1298_Mean_Mem40_MFCC_10    202 non-null    float64
 46  Std_Acc1298_Mean_Mem40_MFCC_11    202 non-null    float64
 47  Std_Acc1298_Mean_Mem40_MFCC_12    202 non-null    float64
 48  Std_Acc1298_Std_Mem40_Centroid    202 non-null    float64
 49  Std_Acc1298_Std_Mem40_Rolloff     202 non-null    float64
 50  Std_Acc1298_Std_Mem40_Flux        202 non-null    float64
 51  Std_Acc1298_Std_Mem40_MFCC_0      202 non-null    float64
 52  Std_Acc1298_Std_Mem40_MFCC_1      202 non-null    float64
 53  Std_Acc1298_Std_Mem40_MFCC_2      202 non-null    float64
 54  Std_Acc1298_Std_Mem40_MFCC_3      202 non-null    float64
 55  Std_Acc1298_Std_Mem40_MFCC_4      202 non-null    float64
 56  Std_Acc1298_Std_Mem40_MFCC_5      202 non-null    float64
 57  Std_Acc1298_Std_Mem40_MFCC_6      202 non-null    float64
 58  Std_Acc1298_Std_Mem40_MFCC_7      202 non-null    float64
 59  Std_Acc1298_Std_Mem40_MFCC_8      202 non-null    float64
 60  Std_Acc1298_Std_Mem40_MFCC_9      202 non-null    float64
 61  Std_Acc1298_Std_Mem40_MFCC_10     202 non-null    float64
 62  Std_Acc1298_Std_Mem40_MFCC_11     202 non-null    float64
 63  Std_Acc1298_Std_Mem40_MFCC_12     202 non-null    float64
 64  BH_LowPeakAmp                     202 non-null    float64
 65  BH_LowPeakBPM                     202 non-null    float64
 66  BH_HighPeakAmp                    202 non-null    float64
 67  BH_HighPeakBPM                    202 non-null    float64
 68  BH_HighLowRatio                   202 non-null    float64
 69  BHSUM1                            202 non-null    float64
 70  BHSUM2                            202 non-null    float64
 71  BHSUM3                            202 non-null    float64
 72  amazed-suprised                   202 non-null    object
 73  happy-pleased                     202 non-null    object
 74  relaxing-calm                     202 non-null    object
 75  quiet-still                       202 non-null    object
 76  sad-lonely                        202 non-null    object
 77  angry-aggresive                   202 non-null    object
dtypes: float64(72), object(6)
memory usage: 123.2+ KB

In [15]:
df_test.head()

,Mean_Acc1298_Mean_Mem40_Centroid,Mean_Acc1298_Mean_Mem40_Rolloff,Mean_Acc1298_Mean_Mem40_Flux,Mean_Acc1298_Mean_Mem40_MFCC_0,Mean_Acc1298_Mean_Mem40_MFCC_1,Mean_Acc1298_Mean_Mem40_MFCC_2,Mean_Acc1298_Mean_Mem40_MFCC_3,Mean_Acc1298_Mean_Mem40_MFCC_4,Mean_Acc1298_Mean_Mem40_MFCC_5,Mean_Acc1298_Mean_Mem40_MFCC_6,...,BH_HighLowRatio,BHSUM1,BHSUM2,BHSUM3,amazed-suprised,happy-pleased,relaxing-calm,quiet-still,sad-lonely,angry-aggresive
0,0.036299,0.064986,0.082104,-72.710462,7.920220,0.134279,2.546373,0.671063,1.589821,0.576485,...,2.0,0.095982,0.520006,0.677943,0,0,1,1,1,0
1,0.161218,0.467820,0.096983,-71.298043,1.176349,1.871744,1.097346,0.641059,0.372797,0.991050,...,2.0,0.752210,0.576382,1.477141,1,0,0,0,0,1
2,0.115987,0.336879,0.079068,-64.570939,2.339044,0.714859,1.792451,0.611347,0.287022,0.772846,...,2.0,0.488375,0.004603,1.147727,0,0,0,0,1,0
3,0.086016,0.141845,0.081554,-81.141092,6.714252,-1.338896,1.326248,0.340032,1.290664,0.337209,...,2.0,0.430059,0.102757,1.276632,0,1,1,0,0,0
4,0.063232,0.140621,0.082097,-66.596131,5.594724,0.350716,1.023655,0.439544,0.855564,0.414784,...,2.0,1.788567,0.032760,3.076057,0,0,0,0,1,0

In [16]:
df_train.to_csv('emotions_train.csv', index=False)

In [17]:
df_test.to_csv('emotions_test.csv', index=False)